version: '3'

services:
  # Streamlit service with Python
  streamlit-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-streamlit-app
    volumes:
      - ./app:/app
    ports:
      - "8501:8501"
    depends_on:
      - elasticsearch

  # Elasticsearch service
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    container_name: my-elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"

networks:
  llm-network:
    driver: bridge